### ISSUE TITLE
Crash when using --authenticate

### ISSUE THREAD

**Issue by Centine** [dfds/ticli#11]
Description: if you are in too much of a hurry and type "cli --authenticate" instead of "cli authenticate", you get a crash. 

No big but might indicate a deeper problem with parameter parsing. 

platform: macbook m1.

Build: Friday 12/4/2024...sometime.

```
12:57:37 ~/Downloads $ ./ticli-darwin-arm64 --authenticate
Error: unknown flag: --authenticate
Usage:
  ticli [command]

Available Commands:
  authenticate Authenticate via Azure AD
  capability   query capabilities
  completion   Generate the autocompletion script for the specified shell
  ecr          Manage Selfservice AWS ECR repositories
  help         Help about any command
  topics       query topics

Flags:
  -t, --access-token string   Provide an access token (or simply run authentication)
      --config string         config file (default is $HOME/.cobra.yaml)
  -h, --help                  help for ticli
      --json                  Json output
      --no-version-check      Disable version check
  -v, --verbose               print moar stuff (default: false)
      --version               version for ticli
      --yaml                  Yaml output

Use "ticli [command] --help" for more information about a command.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1044a05c4]

goroutine 1 [running]:
go.dfds.cloud/ticli/cmds.Execute()
	/home/runner/work/ticli/ticli/cmds/root.go:57 +0x74
main.main()
	/home/runner/work/ticli/ticli/main.go:8 +0x1c
```

**Comment by avnes** [comment]
Closing as fixed in https://github.com/dfds/cloudplatform/issues/2772
